version: '3.9'

services:
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      BACKEND_SETTINGS_DATABASES: '{"default":{"HOST":"db"}}'
      BACKEND_SETTINGS_LOCAL_SETTINGS_PATH: local/settings.prod.py

volumes:
  postgresql-data:
    driver: local
